// <auto-generated />
using System;
using CricPulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CricPulse.Infrastructure.Migrations
{
    [DbContext(typeof(CricPulseDbContext))]
    [Migration("20260912115601_MakePendingRegistrationPasswordOptional")]
    partial class MakePendingRegistrationPasswordOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CricPulse.Domain.Entities.Ball", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallNumber")
                        .HasColumnType("int");

                    b.Property<int>("BowlerMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraRuns")
                        .HasColumnType("int");

                    b.Property<string>("ExtraType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InningsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLegalDelivery")
                        .HasColumnType("bit");

                    b.Property<int>("NonStrikerMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("OverNumber")
                        .HasColumnType("int");

                    b.Property<int>("Runs")
                        .HasColumnType("int");

                    b.Property<int>("StrikerMatchPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BowlerMatchPlayerId");

                    b.HasIndex("InningsId");

                    b.HasIndex("NonStrikerMatchPlayerId");

                    b.HasIndex("StrikerMatchPlayerId");

                    b.ToTable("Balls");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Innings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BattingTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BowlingTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentBowlerMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("InningsNumber")
                        .HasColumnType("int");

                    b.Property<int>("LegalBalls")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("NonStrikerMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrikerMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Wickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBowlerMatchPlayerId");

                    b.HasIndex("MatchId");

                    b.HasIndex("NonStrikerMatchPlayerId");

                    b.HasIndex("StrikerMatchPlayerId");

                    b.ToTable("Innings");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BattingFirstTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LiveStreamUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("MatchTime")
                        .HasColumnType("time");

                    b.Property<int>("Overs")
                        .HasColumnType("int");

                    b.Property<int>("PlayersPerTeam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team1Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team1Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team2Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team2Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TossDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TossWinnerTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UmpireId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UmpireId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtpType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpVerification");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.PendingRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOtpVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OtpExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PendingRegistrations");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BattingStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BowlingStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("PlayerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUmpire")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Wicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallId")
                        .HasColumnType("int");

                    b.Property<int?>("CaughtByMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("DismissedMatchPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RunsCompleted")
                        .HasColumnType("int");

                    b.Property<string>("WicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BallId")
                        .IsUnique();

                    b.HasIndex("CaughtByMatchPlayerId");

                    b.HasIndex("DismissedMatchPlayerId");

                    b.ToTable("Wickets");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Ball", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "BowlerMatchPlayer")
                        .WithMany("BallsAsBowler")
                        .HasForeignKey("BowlerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.Innings", "Innings")
                        .WithMany("Balls")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "NonStrikerMatchPlayer")
                        .WithMany("BallsAsNonStriker")
                        .HasForeignKey("NonStrikerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "StrikerMatchPlayer")
                        .WithMany("BallsAsStriker")
                        .HasForeignKey("StrikerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BowlerMatchPlayer");

                    b.Navigation("Innings");

                    b.Navigation("NonStrikerMatchPlayer");

                    b.Navigation("StrikerMatchPlayer");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Innings", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "CurrentBowlerMatchPlayer")
                        .WithMany()
                        .HasForeignKey("CurrentBowlerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CricPulse.Domain.Entities.Match", "Match")
                        .WithMany("Innings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "NonStrikerMatchPlayer")
                        .WithMany()
                        .HasForeignKey("NonStrikerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "StrikerMatchPlayer")
                        .WithMany()
                        .HasForeignKey("StrikerMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentBowlerMatchPlayer");

                    b.Navigation("Match");

                    b.Navigation("NonStrikerMatchPlayer");

                    b.Navigation("StrikerMatchPlayer");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Match", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.User", "Umpire")
                        .WithMany("MatchesAsUmpire")
                        .HasForeignKey("UmpireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Umpire");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.MatchPlayer", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.OtpVerification", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Player", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("CricPulse.Domain.Entities.Player", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Wicket", b =>
                {
                    b.HasOne("CricPulse.Domain.Entities.Ball", "Ball")
                        .WithOne("Wicket")
                        .HasForeignKey("CricPulse.Domain.Entities.Wicket", "BallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "CaughtByMatchPlayer")
                        .WithMany("Catches")
                        .HasForeignKey("CaughtByMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CricPulse.Domain.Entities.MatchPlayer", "DismissedMatchPlayer")
                        .WithMany("Dismissals")
                        .HasForeignKey("DismissedMatchPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ball");

                    b.Navigation("CaughtByMatchPlayer");

                    b.Navigation("DismissedMatchPlayer");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Ball", b =>
                {
                    b.Navigation("Wicket");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Innings", b =>
                {
                    b.Navigation("Balls");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Match", b =>
                {
                    b.Navigation("Innings");

                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.MatchPlayer", b =>
                {
                    b.Navigation("BallsAsBowler");

                    b.Navigation("BallsAsNonStriker");

                    b.Navigation("BallsAsStriker");

                    b.Navigation("Catches");

                    b.Navigation("Dismissals");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.Player", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("CricPulse.Domain.Entities.User", b =>
                {
                    b.Navigation("MatchesAsUmpire");

                    b.Navigation("OtpVerifications");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
